name: Sync Mixpanel Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: gives the workflow power to make releases
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

   - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt

    - name: Run script
      run: python your_script_name.py
      env:
        MIXPANEL_USER: ${{ secrets.MIXPANEL_USER }}
        MIXPANEL_SECRET: ${{ secrets.MIXPANEL_SECRET }}

    - name: Upload Data to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: active_users.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
